In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/insurance_data.csv")

In [4]:
df.head()

,Customer ID,Age,Gender,Marital Status,Occupation,Income Level,Education Level,Geographic Information,Location,Behavioral Data,...,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Risk Profile,Previous Claims History,Credit Score,Driving Record,Life Events,Segmentation Group
0,84966,23,Female,Married,Entrepreneur,70541,Associate Degree,Mizoram,37534,policy5,...,Email,In-Person Meeting,Afternoon,English,1,3,728,DUI,Job Change,Segment5
1,95568,26,Male,Widowed,Manager,54168,Doctorate,Goa,63304,policy5,...,Mail,In-Person Meeting,Morning,French,1,2,792,Clean,Retirement,Segment5
2,10544,29,Female,Single,Entrepreneur,73899,Associate Degree,Rajasthan,53174,policy5,...,Email,Mail,Evening,German,2,1,719,Accident,Childbirth,Segment3
3,77033,20,Male,Divorced,Entrepreneur,63381,Bachelor's Degree,Sikkim,22803,policy5,...,Text,In-Person Meeting,Anytime,French,3,0,639,DUI,Job Change,Segment3
4,88160,25,Female,Separated,Manager,38794,Bachelor's Degree,West Bengal,92858,policy1,...,Email,Text,Weekends,English,0,3,720,Major Violations,Childbirth,Segment2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  object
 3   Marital Status                      53503 non-null  object
 4   Occupation                          53503 non-null  object
 5   Income Level                        53503 non-null  int64
 6   Education Level                     53503 non-null  object
 7   Geographic Information              53503 non-null  object
 8   Location                            53503 non-null  int64
 9   Behavioral Data                     53503 non-null  object
 10  Purchase History                    53503 non-null  object
 11  Policy Start Date                   53503 non-null  object
 12  Policy Renewal Date                 53503 non-null  object
 13  Claim History                       53503 non-null  int64
 14  Interactions with Customer Service  53503 non-null  object
 15  Insurance Products Owned            53503 non-null  object
 16  Coverage Amount                     53503 non-null  int64
 17  Premium Amount                      53503 non-null  int64
 18  Deductible                          53503 non-null  int64
 19  Policy Type                         53503 non-null  object
 20  Customer Preferences                53503 non-null  object
 21  Preferred Communication Channel     53503 non-null  object
 22  Preferred Contact Time              53503 non-null  object
 23  Preferred Language                  53503 non-null  object
 24  Risk Profile                        53503 non-null  int64
 25  Previous Claims History             53503 non-null  int64
 26  Credit Score                        53503 non-null  int64
 27  Driving Record                      53503 non-null  object
 28  Life Events                         53503 non-null  object
 29  Segmentation Group                  53503 non-null  object
dtypes: int64(11), object(19)
memory usage: 12.2+ MB

In [6]:
df.describe()

,Customer ID,Age,Income Level,Location,Claim History,Coverage Amount,Premium Amount,Deductible,Risk Profile,Previous Claims History,Credit Score
count,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000
mean,52265.204998,44.140945,82768.324318,53703.032017,2.522382,492580.789638,3023.702447,1115.662953,1.597107,1.669495,673.318562
std,28165.000067,15.079486,36651.075670,25404.953911,1.749397,268405.505571,1285.834295,560.102855,1.135433,1.097238,99.226674
min,1.000000,18.000000,20001.000000,10000.000000,0.000000,50001.000000,500.000000,100.000000,0.000000,0.000000,500.000000
25%,28950.500000,32.000000,51568.500000,31510.500000,1.000000,249613.500000,1817.000000,668.000000,1.000000,1.000000,586.000000
50%,55858.000000,43.000000,80719.000000,55143.000000,3.000000,477261.000000,3194.000000,1129.000000,1.000000,2.000000,668.000000
75%,76096.000000,57.000000,115973.500000,74951.000000,4.000000,739124.000000,4311.500000,1618.000000,3.000000,3.000000,753.000000
max,100000.000000,70.000000,149999.000000,99999.000000,5.000000,1000000.000000,5000.000000,2000.000000,3.000000,3.000000,850.000000

In [7]:
df.isnull().sum()

Customer ID                           0
Age                                   0
Gender                                0
Marital Status                        0
Occupation                            0
Income Level                          0
Education Level                       0
Geographic Information                0
Location                              0
Behavioral Data                       0
Purchase History                      0
Policy Start Date                     0
Policy Renewal Date                   0
Claim History                         0
Interactions with Customer Service    0
Insurance Products Owned              0
Coverage Amount                       0
Premium Amount                        0
Deductible                            0
Policy Type                           0
Customer Preferences                  0
Preferred Communication Channel       0
Preferred Contact Time                0
Preferred Language                    0
Risk Profile                          0
Previous Claims History               0
Credit Score                          0
Driving Record                        0
Life Events                           0
Segmentation Group                    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower().str.replace(" ", "_")   # Clean dataset

df.head()

,customer_id,age,gender,marital_status,occupation,income_level,education_level,geographic_information,location,behavioral_data,...,customer_preferences,preferred_communication_channel,preferred_contact_time,preferred_language,risk_profile,previous_claims_history,credit_score,driving_record,life_events,segmentation_group
0,84966,23,Female,Married,Entrepreneur,70541,Associate Degree,Mizoram,37534,policy5,...,Email,In-Person Meeting,Afternoon,English,1,3,728,DUI,Job Change,Segment5
1,95568,26,Male,Widowed,Manager,54168,Doctorate,Goa,63304,policy5,...,Mail,In-Person Meeting,Morning,French,1,2,792,Clean,Retirement,Segment5
2,10544,29,Female,Single,Entrepreneur,73899,Associate Degree,Rajasthan,53174,policy5,...,Email,Mail,Evening,German,2,1,719,Accident,Childbirth,Segment3
3,77033,20,Male,Divorced,Entrepreneur,63381,Bachelor's Degree,Sikkim,22803,policy5,...,Text,In-Person Meeting,Anytime,French,3,0,639,DUI,Job Change,Segment3
4,88160,25,Female,Separated,Manager,38794,Bachelor's Degree,West Bengal,92858,policy1,...,Email,Text,Weekends,English,0,3,720,Major Violations,Childbirth,Segment2

In [9]:
df = df.drop_duplicates()

In [10]:
# df["policy_start_date"] = pd.to_datetime(df["policy_start_date"])

In [11]:
df.to_csv("../data/processed/insurance_clean.csv", index=False) # Save Cleaned Dataset to processed folder

In [12]:
import sqlite3

conn = sqlite3.connect("../insurance.db")

In [13]:
df.to_sql("insurance_policies", conn, if_exists="replace", index=False)

53503

In [14]:
query = """
SELECT
    policy_type,
    AVG(premium_amount) AS avg_premium,
    AVG(claim_history) AS avg_claim_history,
    AVG(risk_profile) AS avg_risk
FROM insurance_policies
GROUP BY policy_type
"""

result = pd.read_sql(query, conn)

result

  policy_type  avg_premium  avg_claim_history  avg_risk
0    Business  3036.446661           2.470470  1.608609
1      Family  2964.365100           2.498149  1.605441
2       Group  3045.789208           2.576938  1.573596
3  Individual  3041.327789           2.525911  1.615750

In [15]:
# Create age groups
df["age_group"] = pd.cut(
    df["age"],
    bins=[17, 25, 35, 45, 55, 65, 100],
    labels=["18-25", "26-35", "36-45", "46-55", "56-65", "65+"]
)

# Create credit score groups
df["credit_score_group"] = pd.cut(
    df["credit_score"],
    bins=[0, 580, 670, 740, 800, 900],
    labels=["Poor", "Fair", "Good", "Very Good", "Excellent"]
)

# Create premium to coverage ratio
df["premium_coverage_ratio"] = df["premium_amount"] / df["coverage_amount"]

# Create estimated customer value
df["estimated_value"] = df["premium_amount"] * (1 + df["risk_profile"])

# Create risk category
df["risk_category"] = pd.cut(
    df["risk_profile"],
    bins=[-1, 0, 1, 2, 3],
    labels=["Very Low", "Low", "Medium", "High"]
)

In [16]:
df.to_csv("../data/processed/insurance_clean.csv", index=False)